#pragma config(Sensor, in1,    LiftPOT,        sensorPotentiometer)
#pragma config(Sensor, dgtl9,  Left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Right,          sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftRear,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Mystery,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Empty,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RightRear,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	SensorValue[Left] = 0;
	SensorValue[Right] = 0;
	SensorValue[LiftPOT] = 975;
	while (abs (SensorValue[Right]) < 300) {
		motor[RightFront]  = 110;
		motor[LeftFront] =110;
		motor[LeftRear] = 110;
		motor[RightRear] = 110;

		if (abs (SensorValue[LiftPOT]) < 2200) {
			motor[LeftLift] = 40;
			motor[RightLift] = 40;
		}
			if (abs(SensorValue[LiftPOT]) > 2200){
				motor[LeftLift] = 0;
				motor[RightLift] = 0;
}
			}



		while (abs (SensorValue[Right]) >= 300 ){
			motor[RightFront]  = 80;
			motor[LeftFront] = -80;
			motor[LeftRear] = -80;
			motor[RightRear] = 80;
			if (abs (SensorValue[LiftPOT]) > 1500) {
				motor[LeftLift] = -110;
				motor[RightLift] = -110;
			}
			if (abs (SensorValue[LiftPOT]) < 1500) {
				motor[LeftLift] = 0;
				motor[RightLift] = 0;
			}
			while (abs (SensorValue[Right]) == 440) {
				motor[RightFront]  = 0;
				motor[LeftFront] = 0;
				motor[LeftRear] = 0;
				motor[RightRear] = 0;
			}
					while (abs (SensorValue[Right]) > 440) {
				motor[RightFront]  = 80;
				motor[LeftFront] = 80;
				motor[LeftRear] = 80;
				motor[RightRear] = 80;
				while (abs (SensorValue[Right]) > 730) {
				motor[RightFront]  = 50;
				motor[LeftFront] = 10;
				motor[LeftRear] = 10;
				motor[RightRear] = 50;
				while (abs (SensorValue[Right]) == 835) {
			motor[RightFront]  = 0;
				motor[LeftFront] = 0;
				motor[LeftRear] = 0;
				motor[RightRear] = 0;
			}
				while (abs (SensorValue[Right]) >= 835) {
			motor[RightFront]  = -20;
				motor[LeftFront] = -20;
				motor[LeftRear] = -20;
				motor[RightRear] = -20;
					if (abs (SensorValue[LiftPOT]) < 2270) {
			motor[LeftLift] = 40;
			motor[RightLift] = 40;
		}
			if (abs(SensorValue[LiftPOT]) > 2270){
				motor[LeftLift] = 0;
				motor[RightLift] = 0;
}
			}
				}
			}

			}
		}



	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			motor[LeftRear] = vexRT[Ch3];
			motor[LeftFront] = vexRT[Ch3];
			motor[RightFront] = vexRT[Ch2];
			motor[RightRear] = vexRT[Ch2];
			if(vexRT[Btn7U] == 1)    {

				motor[RightLift] = -120;    }

			else if(vexRT[Btn7D] == 1)    {

				motor[RightLift] = 120;    }

			else    {

				motor[RightLift] = 0;    }
			if(vexRT[Btn7U] == 1)    {

				motor[LeftLift] = -120;    }

			else if(vexRT[Btn7D] == 1)    {

				motor[LeftLift] = 120;    }

			else    {

				motor[LeftLift] = 0;    }
		}
	}
