#pragma config(Sensor, dgtl9,  leftWheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightWheelEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoal,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	SensorValue[leftWheelEncoder] = 0;
	SensorValue[rightWheelEncoder] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	while(true)
	{
		while(SensorValue[leftWheelEncoder] < 720)//while it hasnt travelled 2 rotations
		{
			if(SensorValue[leftWheelEncoder] < SensorValue[rightWheelEncoder])//if left side is lagging behind
			{
				motor[backLeft] = 127;
				motor[frontLeft] = 127;
				motor[backRight] = 100;
				motor[backRight] = 100;
			}
			else if(SensorValue[leftWheelEncoder] < SensorValue[rightWheelEncoder])//if left side is lagging behind
			{
				motor[backLeft] = 100;
				motor[frontLeft] = 100;
				motor[backRight] = 127;
				motor[backRight] = 127;
			}
			else//Encoders are equal
			{
				motor[backLeft] = 127;
				motor[frontLeft] = 127;
				motor[backRight] = 127;
				motor[backRight] = 127;
			}
		}
	}
}
	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			//Right side of the robot is controlled by the right joystick, Y-axis
			motor[frontRight] = vexRT[Ch2];
			motor[backRight]  = vexRT[Ch2];
			//Left side of the robot is controlled by the left joystick, Y-axis
			motor[frontLeft] = vexRT[Ch3];
			motor[backLeft]  = vexRT[Ch3];
			//claw lift code
			if(vexRT[Btn5U] == 1)
			{
				motor[rightLift] = 127;
				motor[leftLift] = 127;
			}
			else if(vexRT[Btn5D] == 1)
			{
				motor[rightLift] = -127;
				motor[leftLift] = -127;
			}
			else
			{
				motor[rightLift] = 0;
				motor[leftLift] = 0;
			}
			//claw code
			if(vexRT[Btn6U] == 1) //Button 6 up is pressed, close claw
			{
				motor[claw] = 127;
			}

			else if(vexRT[Btn6D] == 1) //Button 6 down is pressed, open claw
			{
				motor[claw] = -100;
			}

			else //If neither is pressed, stop motors
			{
				motor[claw] = 0;
			}
			//mobile lift code
			if(vexRT[Btn7U] == 1)
			{
				motor[mobileGoal] = 63;
			}
			else if(vexRT[Btn7D] == 1)
			{
				motor[mobileGoal] = -63;
			}
			else
				motor[mobileGoal] = 0;
		}
	}
