#pragma config(Sensor, dgtl9,  leftWheelEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightWheelEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoal,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	wait1Msec(1000);  // 1 Second Delay

	//Clear Encoders
	SensorValue[rightWheelEncoder] = 0;
	SensorValue[leftWheelEncoder] = 0;
	while(true)
	{
		while(SensorValue[leftWheelEncoder] < 350)
		{
			if(SensorValue[leftWheelEncoder] < SensorValue[rightWheelEncoder])//if right side is behind
			{
				motor[backLeft] = 63;
				motor[backRight] = 50;
				motor[frontLeft] = 63;
				motor[frontRight] = 50;
			}
			else if(SensorValue[rightWheelEncoder] < SensorValue[leftWheelEncoder])//if left side is behind
			{
				motor[backLeft] = 40;
				motor[backRight] = 63;
				motor[frontLeft] = 63;
				motor[frontRight] = 40;
			}
			else
			{
				//...Move Forward
				motor[backLeft] = 63;
				motor[backRight] = 63;
				motor[frontLeft] = 63;
				motor[frontRight] = 63;
			}
		}
		motor[backLeft] = 0;
		motor[backRight] = 0;
		motor[frontLeft] = 0;
		motor[frontRight] = 0;
		wait1Msec(1000);  // 1 Second Delay

	//Clear Encoders
	SensorValue[rightWheelEncoder] = 0;
	SensorValue[leftWheelEncoder] = 0;
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[frontRight] = vexRT[Ch2];
		motor[backRight]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[frontLeft] = vexRT[Ch3];
		motor[backLeft]  = vexRT[Ch3];
		//claw lift code
		if(vexRT[Btn5U] == 1)
		{
			motor[rightLift] = 127;
			motor[leftLift] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[rightLift] = -127;
			motor[leftLift] = -127;
		}
		else
		{
			motor[rightLift] = 0;
			motor[leftLift] = 0;
		}
		//claw code
		if(vexRT[Btn6U] == 1) //Button 6 up is pressed, close claw
		{
			motor[claw] = 127;
		}

		else if(vexRT[Btn6D] == 1) //Button 6 down is pressed, open claw
		{
			motor[claw] = -100;
		}

		else //If neither is pressed, stop motors
		{
			motor[claw] = 0;
		}
		//mobile lift code
		if(vexRT[Btn7U] == 1)
		{
			motor[mobileGoal] = 63;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[mobileGoal] = -63;
		}
		else
			motor[mobileGoal] = 0;
	}
}
